## This is a launchpad made from python and pyqt5 designer ##

from PyQt5 import QtCore, QtGui, QtWidgets
import moviepy.editor as py
import webbrowser
import pyautogui as py
import time
import os
from tkinter import filedialog
from tkinter import *
import win32com.client as wincl
speak = wincl.Dispatch("SAPI.SpVoice")
from pygame import mixer
import psutil
from tkinter.ttk import*
from time import strftime


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1350, 680)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(580, 0, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 340, 101, 101))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("PNG/Find My.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(630, 140, 81, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(950, 490, 101, 101))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("PNG/Settings.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 40, 101, 101))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("PNG/Google.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 140, 81, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(180, 40, 101, 101))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("PNG/Google Gmail.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(290, 400, 47, 13))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(510, 40, 101, 101))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("PNG/YouTube.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(620, 40, 101, 101))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("PNG/YouTube Music.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(400, 40, 101, 101))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("PNG/Microsoft Edge.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(70, 190, 101, 101))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("PNG/Microsoft PowerPoint.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(180, 190, 101, 101))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("PNG/Microsoft OneNote.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(290, 190, 101, 101))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("PNG/Microsoft Word.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(400, 190, 101, 101))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("PNG/Microsoft Excell.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(510, 190, 101, 101))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("PNG/Microsoft ToDo.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(70, 340, 101, 101))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("PNG/Microsoft Groove.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(620, 190, 101, 101))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("PNG/Microsoft Visual Studio Code.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(190, 140, 81, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 140, 81, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(410, 140, 81, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(520, 140, 81, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(80, 290, 81, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(190, 290, 81, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(300, 290, 81, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(410, 290, 81, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(520, 290, 81, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(630, 290, 81, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(80, 440, 81, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(190, 440, 81, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(290, 340, 101, 101))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("PNG/Calculator.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(300, 440, 81, 23))
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(400, 340, 101, 101))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("PNG/Calendar.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(410, 440, 81, 23))
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(510, 340, 101, 101))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("PNG/Flume.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(620, 340, 101, 101))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("PNG/Notes.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(520, 440, 81, 23))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(630, 440, 81, 23))
        self.pushButton_18.setObjectName("pushButton_18")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(70, 490, 101, 101))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("PNG/Finder.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(80, 590, 81, 23))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(190, 590, 81, 23))
        self.pushButton_20.setObjectName("pushButton_20")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(180, 490, 101, 101))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("PNG/GitHub Desktop.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(510, 490, 101, 101))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("PNG/Screenshot.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(300, 590, 81, 23))
        self.pushButton_21.setObjectName("pushButton_21")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(290, 490, 101, 101))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("PNG/Kindle.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(400, 490, 101, 101))
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("PNG/QR Encoder.png"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(410, 590, 81, 23))
        self.pushButton_22.setObjectName("pushButton_22")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(620, 490, 101, 101))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("PNG/Stremio.png"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(520, 590, 81, 23))
        self.pushButton_23.setObjectName("pushButton_23")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(840, 40, 101, 101))
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("PNG/Sky Go.png"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24.setGeometry(QtCore.QRect(630, 590, 81, 23))
        self.pushButton_24.setObjectName("pushButton_24")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(840, 340, 101, 101))
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("PNG/Whatsapp.png"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_25.setGeometry(QtCore.QRect(850, 140, 81, 23))
        self.pushButton_25.setObjectName("pushButton_25")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(840, 190, 101, 101))
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("PNG/Voice Memos.png"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setGeometry(QtCore.QRect(850, 290, 81, 23))
        self.pushButton_26.setObjectName("pushButton_26")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(950, 190, 101, 101))
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap("PNG/Zoom.png"))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName("label_30")
        self.pushButton_27 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_27.setGeometry(QtCore.QRect(850, 440, 81, 23))
        self.pushButton_27.setObjectName("pushButton_27")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(950, 40, 101, 101))
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap("PNG/Siri.png"))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName("label_31")
        self.pushButton_28 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_28.setGeometry(QtCore.QRect(960, 290, 81, 23))
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_29.setGeometry(QtCore.QRect(960, 140, 81, 23))
        self.pushButton_29.setObjectName("pushButton_29")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(730, 40, 101, 101))
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("PNG/Terminal.png"))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(730, 190, 101, 101))
        self.label_34.setText("")
        self.label_34.setPixmap(QtGui.QPixmap("PNG/Music.png"))
        self.label_34.setScaledContents(True)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(730, 340, 101, 101))
        self.label_35.setText("")
        self.label_35.setPixmap(QtGui.QPixmap("PNG/AppCleaner.png"))
        self.label_35.setScaledContents(True)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(730, 490, 101, 101))
        self.label_36.setText("")
        self.label_36.setPixmap(QtGui.QPixmap("PNG/PyCharm.png"))
        self.label_36.setScaledContents(True)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(840, 490, 101, 101))
        self.label_37.setText("")
        self.label_37.setPixmap(QtGui.QPixmap("PNG/IntelliJ Idea.png"))
        self.label_37.setScaledContents(True)
        self.label_37.setObjectName("label_37")
        self.pushButton_31 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_31.setGeometry(QtCore.QRect(740, 140, 81, 23))
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_32.setGeometry(QtCore.QRect(740, 290, 81, 23))
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_33 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_33.setGeometry(QtCore.QRect(740, 440, 81, 23))
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_34 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_34.setGeometry(QtCore.QRect(740, 590, 81, 23))
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_35 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_35.setGeometry(QtCore.QRect(850, 590, 81, 23))
        self.pushButton_35.setObjectName("pushButton_35")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(70, 40, 101, 101))
        self.label_38.setText("")
        self.label_38.setPixmap(QtGui.QPixmap("PNG/Microsoft Windows.png"))
        self.label_38.setScaledContents(True)
        self.label_38.setObjectName("label_38")
        self.pushButton_36 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_36.setGeometry(QtCore.QRect(960, 590, 81, 23))
        self.pushButton_36.setObjectName("pushButton_36")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(950, 340, 101, 101))
        self.label_39.setText("")
        self.label_39.setPixmap(QtGui.QPixmap("PNG/Eclipse.png"))
        self.label_39.setScaledContents(True)
        self.label_39.setObjectName("label_39")
        self.pushButton_37 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_37.setGeometry(QtCore.QRect(960, 440, 81, 23))
        self.pushButton_37.setObjectName("pushButton_37")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(1060, 40, 101, 101))
        self.label_32.setText("")
        self.label_32.setPixmap(QtGui.QPixmap("PNG/Photos.png"))
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName("label_32")
        self.pushButton_30 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_30.setGeometry(QtCore.QRect(1070, 140, 81, 23))
        self.pushButton_30.setObjectName("pushButton_30")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(1060, 190, 101, 101))
        self.label_40.setText("")
        self.label_40.setPixmap(QtGui.QPixmap("PNG/Battery Monitor.png"))
        self.label_40.setScaledContents(True)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(1060, 340, 101, 101))
        self.label_41.setText("")
        self.label_41.setPixmap(QtGui.QPixmap("PNG/Atom.png"))
        self.label_41.setScaledContents(True)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(1060, 490, 101, 101))
        self.label_42.setText("")
        self.label_42.setPixmap(QtGui.QPixmap("PNG/Files.png"))
        self.label_42.setScaledContents(True)
        self.label_42.setObjectName("label_42")
        self.pushButton_38 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_38.setGeometry(QtCore.QRect(1070, 290, 81, 23))
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_39 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_39.setGeometry(QtCore.QRect(1070, 440, 81, 23))
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_40 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_40.setGeometry(QtCore.QRect(1070, 590, 81, 23))
        self.pushButton_40.setObjectName("pushButton_40")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(1170, 40, 101, 101))
        self.label_43.setText("")
        self.label_43.setPixmap(QtGui.QPixmap("PNG/Be Focused.png"))
        self.label_43.setScaledContents(True)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(1170, 190, 101, 101))
        self.label_44.setText("")
        self.label_44.setPixmap(QtGui.QPixmap("PNG/ScreenBrush.png"))
        self.label_44.setScaledContents(True)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(1170, 340, 101, 101))
        self.label_45.setText("")
        self.label_45.setPixmap(QtGui.QPixmap("PNG/Disk Diet.png"))
        self.label_45.setScaledContents(True)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(1170, 490, 101, 101))
        self.label_46.setText("")
        self.label_46.setPixmap(QtGui.QPixmap("PNG/EXEC File.png"))
        self.label_46.setScaledContents(True)
        self.label_46.setObjectName("label_46")
        self.pushButton_41 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_41.setGeometry(QtCore.QRect(1180, 140, 81, 23))
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_42 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_42.setGeometry(QtCore.QRect(1180, 290, 81, 23))
        self.pushButton_42.setObjectName("pushButton_42")
        self.pushButton_43 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_43.setGeometry(QtCore.QRect(1180, 440, 81, 23))
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_44 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_44.setGeometry(QtCore.QRect(1180, 590, 81, 23))
        self.pushButton_44.setObjectName("pushButton_44")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1278, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        ### replace start with the function ###
        
        self.pushButton.clicked.connect(lambda: self.ytmusic())
        self.pushButton_2.clicked.connect(lambda: self.start())
        self.pushButton_3.clicked.connect(lambda: self.gmail())
        self.pushButton_4.clicked.connect(lambda: self.google())
        self.pushButton_5.clicked.connect(lambda: self.edge())
        self.pushButton_6.clicked.connect(lambda: self.youtube())
        self.pushButton_7.clicked.connect(lambda: self.powerpoint())
        self.pushButton_8.clicked.connect(lambda: self.onenote())
        self.pushButton_9.clicked.connect(lambda: self.word())
        self.pushButton_10.clicked.connect(lambda: self.excel())
        self.pushButton_11.clicked.connect(lambda: self.todolist())
        self.pushButton_12.clicked.connect(lambda: self.vscode())
        self.pushButton_13.clicked.connect(lambda: self.groovemusic())
        self.pushButton_14.clicked.connect(lambda: self.ciscowebex())
        self.pushButton_15.clicked.connect(lambda: self.calculator())
        self.pushButton_16.clicked.connect(lambda: self.calendar())
        self.pushButton_17.clicked.connect(lambda: self.camera())
        self.pushButton_18.clicked.connect(lambda: self.notepad())
        self.pushButton_19.clicked.connect(lambda: self.fileexplorer())
        self.pushButton_20.clicked.connect(lambda: self.github())
        self.pushButton_21.clicked.connect(lambda: self.kindle())
        self.pushButton_22.clicked.connect(lambda: self.qrcodescan())
        self.pushButton_23.clicked.connect(lambda: self.screenshot())
        self.pushButton_24.clicked.connect(lambda: self.jarvisvideos())
        self.pushButton_25.clicked.connect(lambda: self.movies())
        self.pushButton_26.clicked.connect(lambda: self.recorder())
        self.pushButton_27.clicked.connect(lambda: self.whatsapp())
        self.pushButton_28.clicked.connect(lambda: self.zoom())
        self.pushButton_29.clicked.connect(lambda: self.cortana())
        self.pushButton_30.clicked.connect(lambda: self.pictures())
        self.pushButton_31.clicked.connect(lambda: self.terminal())
        self.pushButton_32.clicked.connect(lambda: self.jarvismusic())
        self.pushButton_33.clicked.connect(lambda: self.recyclebin())
        self.pushButton_34.clicked.connect(lambda: self.pythonidle())
        self.pushButton_35.clicked.connect(lambda: self.bluej())
        self.pushButton_36.clicked.connect(lambda: self.settings())
        self.pushButton_37.clicked.connect(lambda: self.eclipse())
        self.pushButton_38.clicked.connect(lambda: self.battery())
        self.pushButton_39.clicked.connect(lambda: self.atom())
        self.pushButton_40.clicked.connect(lambda: self.ultrafolder())
        self.pushButton_41.clicked.connect(lambda: self.clock())
        self.pushButton_42.clicked.connect(lambda: self.paint())
        self.pushButton_43.clicked.connect(lambda: self.localdisk())
        self.pushButton_44.clicked.connect(lambda: self.pythonall())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Jarvis Launchpad"))
        MainWindow.setWindowIcon(QtGui.QIcon('C:\\Users\\joels\\Desktop\\Jarvis v2.0\\Customization\\jarvis.jpg'))
        self.label.setText(_translate("MainWindow", "Jarvis Launchpad "))
        self.pushButton.setText(_translate("MainWindow", "Yt Music"))
        self.pushButton_2.setText(_translate("MainWindow", "Start"))
        self.pushButton_3.setText(_translate("MainWindow", "Gmail"))
        self.pushButton_4.setText(_translate("MainWindow", "Google"))
        self.pushButton_5.setText(_translate("MainWindow", "Edge"))
        self.pushButton_6.setText(_translate("MainWindow", "Youtube"))
        self.pushButton_7.setText(_translate("MainWindow", "Powerpoint"))
        self.pushButton_8.setText(_translate("MainWindow", "One Note"))
        self.pushButton_9.setText(_translate("MainWindow", "Word"))
        self.pushButton_10.setText(_translate("MainWindow", "Excel"))
        self.pushButton_11.setText(_translate("MainWindow", "To Do List"))
        self.pushButton_12.setText(_translate("MainWindow", "V S Code"))
        self.pushButton_13.setText(_translate("MainWindow", "Groove music"))
        self.pushButton_14.setText(_translate("MainWindow", "Cisco Webex"))
        self.pushButton_15.setText(_translate("MainWindow", "Calculator"))
        self.pushButton_16.setText(_translate("MainWindow", "Calendar"))
        self.pushButton_17.setText(_translate("MainWindow", "Camera"))
        self.pushButton_18.setText(_translate("MainWindow", "Notepad"))
        self.pushButton_19.setText(_translate("MainWindow", "File Explorer"))
        self.pushButton_20.setText(_translate("MainWindow", "Github"))
        self.pushButton_21.setText(_translate("MainWindow", "Kindle"))
        self.pushButton_22.setText(_translate("MainWindow", "Get qrcode"))
        self.pushButton_23.setText(_translate("MainWindow", "Screenshot"))
        self.pushButton_24.setText(_translate("MainWindow", "Jarvis videos"))
        self.pushButton_25.setText(_translate("MainWindow", "Movies"))
        self.pushButton_26.setText(_translate("MainWindow", "Recorder"))
        self.pushButton_27.setText(_translate("MainWindow", "Whatsapp"))
        self.pushButton_28.setText(_translate("MainWindow", "Zoom"))
        self.pushButton_29.setText(_translate("MainWindow", "Cortana"))
        self.pushButton_30.setText(_translate("MainWindow", "Pictures"))
        self.pushButton_31.setText(_translate("MainWindow", "Terminal"))
        self.pushButton_32.setText(_translate("MainWindow", "Jarvis music"))
        self.pushButton_33.setText(_translate("MainWindow", "Recycle Bin"))
        self.pushButton_34.setText(_translate("MainWindow", "Python IDLE"))
        self.pushButton_35.setText(_translate("MainWindow", "Blue J"))
        self.pushButton_36.setText(_translate("MainWindow", "Settings"))
        self.pushButton_37.setText(_translate("MainWindow", "Eclipse"))
        self.pushButton_38.setText(_translate("MainWindow", "Battery"))
        self.pushButton_39.setText(_translate("MainWindow", "Atom"))
        self.pushButton_40.setText(_translate("MainWindow", "Ultra Folder"))
        self.pushButton_41.setText(_translate("MainWindow", "Clock"))
        self.pushButton_42.setText(_translate("MainWindow", "Paint"))
        self.pushButton_43.setText(_translate("MainWindow", "Local Disk"))
        self.pushButton_44.setText(_translate("MainWindow", "Python All"))

    def ytmusic(self):
        speak.Speak("Opening Youtube Music")
        webbrowser.open("https://music.youtube.com/")

    def start(self):
        speak.Speak("Opening Start")
        py.hotkey('winleft')

    def gmail(self):
        speak.Speak("Opening Gmail")
        webbrowser.open("https://mail.google.com/mail/u/0/#inbox")

    def google(self):
        speak.Speak("Opening Google website")
        webbrowser.open("www.google.com")

    def edge(self):
        speak.Speak("Opening Bing website")
        webbrowser.open("https://www.bing.com/")

    def youtube(self):
        speak.Speak("Opening Youtube")
        webbrowser.open("www.youtube.com")

    def powerpoint(self):
        speak.Speak("Opening Powerpoint")
        py.hotkey('winleft')
        time.sleep(2)
        py.typewrite("powerpoint")
        py.typewrite(["enter"])

    def onenote(self):
        speak.Speak("Opening One note")
        py.hotkey('winleft')
        time.sleep(2)
        py.typewrite("one note")
        py.typewrite(["enter"])

    def word(self):
        speak.Speak("Opening Word")
        py.hotkey('winleft')
        time.sleep(2)
        py.typewrite("Word")
        py.typewrite(["enter"])

    def excel(self):
        speak.Speak("Opening Excel")
        py.hotkey('winleft')
        time.sleep(2)
        py.typewrite("Excel")
        py.typewrite(["enter"])

    def todolist(self):
        speak.Speak("Opening To do")
        py.hotkey('winleft')
        time.sleep(2)
        py.typewrite("to do")
        py.typewrite(["enter"])

    def vscode(self):
        speak.Speak("Opening visual studio code")
        py.hotkey('winleft')
        time.sleep(2)
        py.typewrite("vs code")
        py.typewrite(["enter"])
        
    def groovemusic(self):
        speak.Speak("Opening groove music")
        py.hotkey('winleft')
        time.sleep(2)
        py.typewrite("groove music")
        py.typewrite(["enter"])

    def ciscowebex(self):
        speak.Speak("Opening cisco webex")
        webbrowser.open("https://globalpage-prod.webex.com/join?surl=https%3A%2F%2Fsignin.webex.com%2Fcollabs%2F%23%2Fmeetings%2Fjoinbynumber%3F")

    def calculator(self):
        speak.Speak("Opening Calculator")
        py.hotkey('winleft')
        time.sleep(2)
        py.typewrite("calculator")
        py.typewrite(["enter"])

    def calendar(self):
        speak.Speak("Opening Calendar")
        py.hotkey('winleft')
        time.sleep(2)
        py.typewrite("calendar")
        py.typewrite(["enter"])

    def camera(self):
        speak.Speak("Opening Camera")
        py.hotkey('winleft')
        time.sleep(2)
        py.typewrite("camera")
        py.typewrite(["enter"])

    def notepad(self):
        speak.Speak("Opening notepad")
        py.hotkey('winleft')
        time.sleep(2)
        py.typewrite("notepad")
        py.typewrite(["enter"])

    def fileexplorer(self):
        speak.Speak("Opening file explorer")
        py.hotkey('winleft')
        time.sleep(2)
        py.typewrite("file explorer")
        py.typewrite(["enter"])

    def github(self):
        speak.Speak("Opening Github")
        webbrowser.open("https://github.com/")

    def kindle(self):
        speak.Speak("Opening Kindle")
        py.hotkey('winleft')
        time.sleep(2)
        py.typewrite("kindle")
        py.typewrite(["enter"])

    def qrcodescan(self):
        speak.Speak("Opening Qr code generator")
        root = tkinter.Tk()
        root.wm_withdraw()
        root.iconify()

        speak.Speak("What is the url for which you want the qr code ? Please go to the main Launchpad window.")

        print("What is the url for which you want the qr code ?")
        s = input()
        url = pyqrcode.create(s)
        url.svg(filedialog.asksaveasfilename(initialdir = "C:\\Users\\joels\\Desktop\\Jarvis v2.0\\Qr codes",title = "Save qr code",defaultextension='.svg'), scale = 8)

        speak.Speak("Qr code saved successfully !")
        root.destroy()

    def screenshot(self):
        root = tkinter.Tk()
        root.wm_withdraw()
        root.iconify()

        speak.Speak("Preparing to take screenshot. Please go to the main Launchpad window. Please note that your screenshot window should be on the backside of this Jarvis window.")
        print("Please note that your screenshot window should be on the backside of this Jarvis window.")
        print("")
        py.moveTo(1318,373,duration=2)
        py.hotkey('alt','space','n')
        py.moveTo(1318,373,duration=1)
        myScreenshot = py.screenshot()
        myScreenshot.save(filedialog.asksaveasfilename(initialdir = "C:\\Users\\joels\\Desktop\\Jarvis v2.0\\screenshots",title = "Save file",defaultextension='.png'))
        speak.Speak("Screenshot save successfully !")

        root.destroy()

    def jarvisvideos(self):
        speak.Speak("Opening jarvis video player")
        py.hotkey('win','r')
        py.moveTo(946,767,duration=2)
        py.typewrite("cmd")
        py.typewrite(["enter"])
        py.moveTo(946,767,duration=3)
        py.typewrite("cd C:\\Users\\joels\\Desktop\\Jarvis v2.0\\All media players")
        py.typewrite(["enter"])
        py.typewrite("python \"Multimediaplayer.py\"")
        py.typewrite(["enter"])

    def movies(self):
        speak.Speak("Opening Movies and TV")
        py.hotkey('winleft')
        time.sleep(2)
        py.typewrite("movies")
        py.typewrite(["enter"])

    def recorder(self):
        speak.Speak("Opening jarvis voice recorder")
        speak.Speak("Opening Voice Recorder")
        os.startfile("C:\\Users\\joels\\Desktop\\Jarvis v2.0\\Recordingapp\\dist\\Recordingapp\\Recordingapp.exe")

    def whatspapp(self):
        speak.Speak("Opening whatsapp")
        webbrowser.open("https://web.whatsapp.com/")

    def zoom(self):
        speak.Speak("Opening zoom")
        py.hotkey('winleft')
        time.sleep(2)
        py.typewrite("zoom")
        py.typewrite(["enter"])

    def cortana(self):
        speak.Speak("Opening cortana")
        py.hotkey('winleft')
        time.sleep(2)
        py.typewrite("cortana")
        py.typewrite(["enter"])

    def pictures(self):
        speak.Speak("Opening Pictures")
        py.hotkey('winleft')
        time.sleep(2)
        py.typewrite("pictures")
        py.typewrite(["enter"])

    def terminal(self):
        speak.Speak("Opening command prompt")
        py.hotkey('win','r')
        time.sleep(2)
        py.typewrite("cmd")
        py.typewrite(["enter"])

    def jarvismusic(self):

        speak.Speak("Opening jarvis music player")
        py.hotkey('win','r')
        py.moveTo(946,767,duration=2)
        py.typewrite("cmd")
        py.typewrite(["enter"])
        py.moveTo(946,767,duration=3)
        py.typewrite("cd C:\\Users\\joels\\Desktop\\Ultra Folder\\Mega Folder\\Music")
        py.typewrite(["enter"])
        py.typewrite("python \"My Playlist.py\"")
        py.typewrite(["enter"])
        
    def recyclebin(self):
        speak.Speak("Opening recycle bin")
        py.hotkey('winleft')
        time.sleep(2)
        py.typewrite("recycle bin")
        py.typewrite(["enter"])

    def pythonidle(self):
        speak.Speak("Opening Python I D L E")
        py.hotkey('winleft')
        time.sleep(2)
        py.typewrite("idle")
        py.typewrite(["enter"])

    def bluej(self):
        speak.Speak("Opening BlueJ")
        py.hotkey('winleft')
        time.sleep(2)
        py.typewrite("bluej")
        py.typewrite(["enter"])

    def settings(self):
        speak.Speak("Opening Settings")
        py.hotkey('winleft')
        time.sleep(2)
        py.typewrite("settings")
        py.typewrite(["enter"])

    def eclipse(self):
        speak.Speak("Opening eclipse")
        py.hotkey('winleft')
        time.sleep(2)
        py.typewrite("eclipse IDE")
        py.typewrite(["enter"])

    def battery(self):
        speak.Speak("Showing remaining battery")
        battery = psutil.sensors_battery()
        percent = battery.percent
        percentinletters = str(percent)
        speak.Speak("Sir, there is "+percentinletters+" percent remaining. Battery remaining is printed in the main screen.")
        print("There is "+percentinletters+" % remaining.")
        print("")

    def atom(self):
        speak.Speak("Opening Atom")
        py.hotkey('winleft')
        time.sleep(2)
        py.typewrite("Atom")
        py.typewrite(["enter"])

    def ultrafolder(self):
        speak.Speak("Opening Ultra folder")
        os.startfile("C:\\Users\\joels\\Desktop\\Ultra Folder")

    def clock(self):
        speak.Speak("Showing jarvis digital clock")
        top=Tk()
        top.title("Jarvis Digital Clock")
        def none():
            text=strftime(' %H:%M:%S %p ')
            lbl.config(text=text)
            lbl.after(1000,none)
        lbl=Label(top,font=('digital-7',50,'bold'),
                  background='white',foreground='blue')
        lbl.pack(anchor='center')
        none()
        mainloop()

    def paint(self):
        speak.Speak("Opening Paint")
        speak.Speak("Sir, do you want paint or paint 3D ? Please go to the main screen to choose it.")
        print("")
        print("Press p for paint and p3 for paint 3D.")
        paintorthreed = input()
        
        if paintorthreed == "p":
            py.hotkey('winleft')
            time.sleep(2)
            py.typewrite("Microsoft Paint")
            py.typewrite(["enter"])

        if paintorthreed == "p3":
            py.hotkey('winleft')
            time.sleep(2)
            py.typewrite("Paint 3d")
            py.typewrite(["enter"])

    def localdisk(self):
        speak.Speak("Opening C Drive")
        os.startfile("C:\\")

    def pythonall(self):
        speak.Speak("Opening Python All Directory")
        os.startfile("C:\\Python All")
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
